### ISSUE TITLE
items are not receiving data

### ISSUE THREAD

**Issue by lodperera** [Lelik13a/Zabbix-LXC#1]
Hi Mate,

First of all thank you for creating the LXC scripts and templates.
I was able to use them to run the low-level discovery(agent-active) and zabbix linked the LXC template to discovered CTs.

My issue is the newly created CT hosts do not receive data.
How can I troubleshoot this issue?
Any help is appreciated.

regards
LOD

ps I'm using the active agent.

**Comment by Lelik13a** [comment]
Hello.
It may be necessary to wait for a discovery timeout and active agent timeout.
I have not tested the work of an active agent, but should be no problem.
