### ISSUE TITLE
Graph by cgroup/namespace

### ISSUE THREAD

**Issue by alphaonex86** [Lelik13a/Zabbix-LXC#2]
Hello,

I'm very interested by zabbix, but for lxc support I need support of cgroup/namesapce. All graph in one to see quickly the vm in problem (here you have 4 vm: catchchallenger-db-base, catchchallenger-db-common-1-a-master, catchchallenger-db-common-2, catchchallenger-db-login):
http://files.first-world.info/other/lxc_cpu_system-day.png
http://files.first-world.info/other/lxc_cpu_user-day.png
http://files.first-world.info/other/lxc_net-day.png
http://files.first-world.info/other/lxc_ram_used-day.png

Cheers,

**Comment by Lelik13a** [comment]
Hello,
Discovery can only create graphs per VM. Cumulative graphs can be added manually after discovery process.

**Comment by alphaonex86** [comment]
On thousands of vm... any way to do automatically?

**Comment by Lelik13a** [comment]
You can use external script based on zabbix api to achieve this.
Like [https://www.zabbix.com/forum/showthread.php?t=26678](url) or [https://www.zabbix.org/wiki/Python_script_to_create_Screen_from_all_Items/Graphs_of_a_host](url)

**Comment by alphaonex86** [comment]
The problem it's that item is attached to new host, not to the LXC node (host), I don't read perl and pyhton
