### ISSUE TITLE
zabbix v3.2, hosts are not created

### ISSUE THREAD

**Issue by happy-proger** [Lelik13a/Zabbix-LXC#5]
Got a zabbix server v3.2. Now trying to set it up to monitor a proxmox node
Template LXC Node has a discovery rule Discover LXC container . It receives lxc.ct.discovery array from client (zabbix_get shows normal json-like result), and then must create hosts representing lxc containers, getting information from the received data. The problem is that the hosts are not created at all, though no error is fired.

**Comment by mgielissen** [comment]
Did you install sudo?
